[package]
name = "bytecards"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
crypto-bigint = { version = "0.6.1", features = ["alloc"] }
crypto-primes = "0.6.1"
serde = "1.0.218"
